name: Instagram Unfollow

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 15 * * *'

concurrency:
  group: instagram-unfollow
  cancel-in-progress: true

jobs:
  run-unfollow:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true

      - run: node docs/index.js Unfollow

      # âœ… Upload Screenshot
      - name: Upload Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unfollow-screenshots
          path: after_*.png
